-- M1 PostgreSQL baseline schema (version 1).
--
-- Authority: docs/technical/data-model.md (TECH-DATA-001 section 7 table
-- contract), ADR-002 (PostgreSQL + transactional Outbox/Inbox), ADR-001
-- (runner registry), ADR-003 (identity), and the M1-DATA-001 anchor card
-- (User/Team/Membership/Project/Runner/WorkItem/Lease/Execution/AuditEvent/
-- Inbox/Outbox). Every table below traces to DATA-REQ-001..003 or the
-- anchor list; deviations are recorded in migrations/postgresql/README.md.
--
-- Conventions (TECH-DATA-001 sections 6-8):
--   * IDs are UUIDs generated by the application (UUIDv7 preferred).
--   * All timestamps are timestamptz UTC.
--   * Aggregates carry version BIGINT NOT NULL for expected-version CAS.
--   * Every project-scoped child carries project_id; grandchildren use
--     composite foreign keys (DATA-INV-001).
--   * Immutable facts (validation evidence, audit events) are append-only,
--     enforced by triggers (DATA-GATE-002); outbox/inbox envelope columns
--     are immutable while dispatch bookkeeping columns may transition
--     (ADR-002 state machines).

-- ---------------------------------------------------------------------------
-- Identity (ADR-003, SEC-IDENTITY-RBAC)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id           uuid PRIMARY KEY,
    issuer       text NOT NULL,
    subject      text NOT NULL,
    display_name text NOT NULL DEFAULT '',
    status       text NOT NULL DEFAULT 'invited'
        CHECK (status IN ('invited', 'active', 'suspended', 'removed')),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (issuer, subject)
);

CREATE TABLE teams (
    id         uuid PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    status     text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Project-level roles only; platform_admin is a platform grant, never a
-- membership role (permissions.yaml).
CREATE TABLE memberships (
    team_id     uuid NOT NULL REFERENCES teams (id),
    user_id     uuid NOT NULL REFERENCES users (id),
    role        text NOT NULL
        CHECK (role IN ('project_admin', 'coordinator', 'developer', 'verifier', 'viewer')),
    valid_from  timestamptz NOT NULL DEFAULT now(),
    valid_to    timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id)
);
CREATE INDEX idx_memberships_user ON memberships (user_id);

-- ---------------------------------------------------------------------------
-- Projects and work data (anchor M1-DATA-001; DATA-INV-001)
-- ---------------------------------------------------------------------------

CREATE TABLE projects (
    id             uuid PRIMARY KEY,
    team_id        uuid NOT NULL REFERENCES teams (id),
    key            text NOT NULL CHECK (key ~ '^[a-z][a-z0-9-]{2,31}$'),
    name           text NOT NULL,
    description    text NOT NULL DEFAULT '',
    status         text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'configuring', 'active', 'suspended', 'archived')),
    policy_id      uuid,
    policy_version text NOT NULL DEFAULT '',
    config         jsonb NOT NULL DEFAULT '{}'::jsonb,
    version        bigint NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (team_id, key)
);

CREATE TABLE features (
    id             uuid PRIMARY KEY,
    project_id     uuid NOT NULL,
    title          text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
    description    text NOT NULL DEFAULT '',
    reference_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
    status         text NOT NULL DEFAULT 'planning'
        CHECK (status IN ('planning', 'active', 'completed', 'closed')),
    version        bigint NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, id),
    FOREIGN KEY (project_id) REFERENCES projects (id)
);
CREATE INDEX idx_features_project ON features (project_id);

CREATE TABLE work_items (
    id                    uuid PRIMARY KEY,
    project_id            uuid NOT NULL,
    feature_id            uuid,
    type                  text NOT NULL DEFAULT 'task',
    title                 text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
    description           text NOT NULL DEFAULT '',
    status                text NOT NULL DEFAULT 'draft' CHECK (status IN (
        'draft', 'queued', 'leased', 'executing', 'validating',
        'ready_for_human_merge', 'done', 'blocked', 'cancelling',
        'cancelled', 'failed', 'needs_human')),
    priority              text NOT NULL DEFAULT 'normal'
        CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    role                  text,
    dependencies          jsonb NOT NULL DEFAULT '[]'::jsonb,
    test_requirements     jsonb NOT NULL DEFAULT '{}'::jsonb,
    budget                jsonb,
    lease_epoch           bigint NOT NULL DEFAULT 0,
    version               bigint NOT NULL DEFAULT 0,
    creator_principal_id  uuid REFERENCES users (id),
    legacy_session_id     text,
    legacy_worker_id      text,
    merged_at             timestamptz,
    merge_commit_sha      text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, id),
    FOREIGN KEY (project_id) REFERENCES projects (id),
    FOREIGN KEY (project_id, feature_id) REFERENCES features (project_id, id)
);
CREATE INDEX idx_work_items_project_status ON work_items (project_id, status);
CREATE INDEX idx_work_items_role ON work_items (project_id, role, status);
CREATE INDEX idx_work_items_feature ON work_items (project_id, feature_id);

-- ---------------------------------------------------------------------------
-- Runner registry (ADR-001, SEC-RUNNER-SECURITY)
-- ---------------------------------------------------------------------------

CREATE TABLE runners (
    id                uuid PRIMARY KEY,
    display_name      text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 80),
    device_key_hash   text NOT NULL,
    status            text NOT NULL DEFAULT 'pending_approval' CHECK (status IN (
        'pending_approval', 'approved', 'online', 'suspect',
        'offline', 'draining', 'revoked')),
    generation        bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    capabilities      jsonb NOT NULL DEFAULT '[]'::jsonb,
    last_heartbeat_at timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    revoked_at        timestamptz
);

CREATE TABLE runner_bindings (
    project_id uuid NOT NULL,
    runner_id  uuid NOT NULL REFERENCES runners (id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, runner_id),
    FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE runner_enrollments (
    id          uuid PRIMARY KEY,
    project_id  uuid NOT NULL,
    code_hash   text NOT NULL,
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    created_by  uuid NOT NULL REFERENCES users (id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (project_id) REFERENCES projects (id)
);
CREATE INDEX idx_runner_enrollments_expiry ON runner_enrollments (expires_at);

-- ---------------------------------------------------------------------------
-- Leases and executions (DATA-INV-002; runner-security section 6)
-- ---------------------------------------------------------------------------

-- Persisted lease enum is exactly active/completed/released/expired/
-- cancelled; M1 dispatch offer/accept is protocol state, not a second enum.
CREATE TABLE leases (
    id                    uuid PRIMARY KEY,
    project_id            uuid NOT NULL,
    work_item_id          uuid NOT NULL,
    runner_id             uuid REFERENCES runners (id),
    legacy_session_id     text,
    legacy_worker_id      text,
    epoch                 bigint NOT NULL CHECK (epoch > 0),
    connection_generation bigint NOT NULL DEFAULT 1 CHECK (connection_generation > 0),
    nonce_hash            text,
    status                text NOT NULL CHECK (status IN (
        'active', 'completed', 'released', 'expired', 'cancelled')),
    attempt               integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
    version               bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    expires_at            timestamptz NOT NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, id),
    FOREIGN KEY (project_id, work_item_id) REFERENCES work_items (project_id, id)
);
-- DATA-INV-002: at most one open lease per work item.
CREATE UNIQUE INDEX idx_leases_one_active
    ON leases (project_id, work_item_id) WHERE status = 'active';
CREATE INDEX idx_leases_expiry ON leases (status, expires_at);

CREATE TABLE executions (
    id           uuid PRIMARY KEY,
    project_id   uuid NOT NULL,
    work_item_id uuid NOT NULL,
    lease_id     uuid,
    runner_id    uuid REFERENCES runners (id),
    attempt      integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
    status       text NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'completed', 'failed', 'cancelled', 'interrupted')),
    started_at   timestamptz,
    ended_at     timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (project_id, work_item_id) REFERENCES work_items (project_id, id),
    FOREIGN KEY (project_id, lease_id) REFERENCES leases (project_id, id)
);
CREATE INDEX idx_executions_work_item ON executions (project_id, work_item_id);

-- ---------------------------------------------------------------------------
-- Worktrees (TECH-WT-001 workspace states; import fidelity)
-- ---------------------------------------------------------------------------

CREATE TABLE worktrees (
    id             uuid PRIMARY KEY,
    project_id     uuid NOT NULL,
    work_item_id   uuid NOT NULL,
    legacy_session_id text,
    workspace_path text,
    branch_name    text NOT NULL DEFAULT '',
    base_commit    text NOT NULL DEFAULT '',
    status         text NOT NULL DEFAULT 'allocated' CHECK (status IN (
        'allocated', 'active', 'sealed', 'submitted', 'stale',
        'merged', 'abandoned', 'quarantined', 'cleanup_pending')),
    generation     bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    version        bigint NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (project_id, work_item_id) REFERENCES work_items (project_id, id)
);
CREATE INDEX idx_worktrees_status ON worktrees (project_id, status);

-- ---------------------------------------------------------------------------
-- Local diagnostic evidence (DATA-REQ-003 immutable; M2 adds CI evidence)
-- ---------------------------------------------------------------------------

CREATE TABLE validation_runs (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_id       uuid NOT NULL,
    work_item_id     uuid NOT NULL,
    attempt          integer NOT NULL CHECK (attempt > 0),
    base_commit      text NOT NULL DEFAULT '',
    source_commit    text NOT NULL DEFAULT '',
    changed_files    jsonb NOT NULL DEFAULT '[]'::jsonb,
    profile_ref      text NOT NULL DEFAULT '',
    policy_version   text NOT NULL DEFAULT '',
    policy_digest    text NOT NULL DEFAULT '',
    evidence_digest  text NOT NULL DEFAULT '',
    workspace_digest text NOT NULL DEFAULT '',
    authority        text NOT NULL DEFAULT 'diagnostic'
        CHECK (authority IN ('diagnostic', 'merge_gate')),
    producer         text NOT NULL DEFAULT 'maestro-local',
    pipeline_id      text,
    job_id           text,
    test_exit_code   integer,
    test_output      text,
    output_truncated boolean NOT NULL DEFAULT false,
    coverage         numeric,
    boundary_ok      boolean NOT NULL DEFAULT false,
    test_ok          boolean NOT NULL DEFAULT false,
    coverage_ok      boolean NOT NULL DEFAULT false,
    result           text NOT NULL,
    error_code       text,
    duration_ms      bigint NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    created_at       timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (project_id, work_item_id) REFERENCES work_items (project_id, id)
);
CREATE UNIQUE INDEX idx_validation_runs_attempt
    ON validation_runs (project_id, work_item_id, attempt);
CREATE INDEX idx_validation_runs_item ON validation_runs (project_id, work_item_id);

-- ---------------------------------------------------------------------------
-- Append-only audit (SEC-IDENTITY-RBAC section 9)
-- ---------------------------------------------------------------------------

CREATE TABLE audit_events (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_principal text NOT NULL,
    delegation_id   text,
    project_id      text,
    action          text NOT NULL,
    resource_type   text NOT NULL,
    resource_id     text,
    decision        text NOT NULL CHECK (decision IN ('allow', 'deny')),
    reason          text,
    policy_version  text,
    token_hash      text,
    correlation_id  text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_events_project_time ON audit_events (project_id, created_at DESC);
CREATE INDEX idx_audit_events_decision ON audit_events (decision, created_at DESC);

-- ---------------------------------------------------------------------------
-- Transactional Outbox / durable Inbox (ADR-002)
-- ---------------------------------------------------------------------------

CREATE TABLE outbox_events (
    event_id       uuid NOT NULL,
    event_type     text NOT NULL CHECK (event_type ~ '^[a-z][a-z0-9_.]+$'),
    event_version  integer NOT NULL CHECK (event_version > 0),
    source         text NOT NULL,
    project_id     text NOT NULL,
    subject        text NOT NULL,
    occurred_at    timestamptz NOT NULL,
    correlation_id text NOT NULL,
    causation_id   text NOT NULL,
    payload_digest text NOT NULL CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'),
    sensitivity    text NOT NULL CHECK (sensitivity IN (
        'public', 'internal', 'confidential', 'restricted')),
    payload        jsonb NOT NULL,
    status         text NOT NULL DEFAULT 'pending' CHECK (status IN (
        'pending', 'sending', 'delivered', 'retry_wait', 'dead_letter')),
    attempts       integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at   timestamptz NOT NULL DEFAULT now(),
    lease_owner    text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id)
);
CREATE INDEX idx_outbox_dispatch ON outbox_events (status, available_at);

CREATE TABLE inbox_events (
    event_id       uuid NOT NULL,
    event_type     text NOT NULL CHECK (event_type ~ '^[a-z][a-z0-9_.]+$'),
    event_version  integer NOT NULL CHECK (event_version > 0),
    source         text NOT NULL,
    project_id     text NOT NULL,
    subject        text NOT NULL,
    occurred_at    timestamptz NOT NULL,
    correlation_id text NOT NULL,
    causation_id   text NOT NULL,
    payload_digest text NOT NULL CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'),
    sensitivity    text NOT NULL CHECK (sensitivity IN (
        'public', 'internal', 'confidential', 'restricted')),
    payload        jsonb NOT NULL,
    status         text NOT NULL DEFAULT 'received' CHECK (status IN (
        'received', 'processing', 'processed', 'retry_wait', 'dead_letter')),
    attempts       integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    processed_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id)
);
CREATE INDEX idx_inbox_dispatch ON inbox_events (status);

-- ---------------------------------------------------------------------------
-- Write-path idempotency (TECH-DATA-001 section 8)
-- ---------------------------------------------------------------------------

CREATE TABLE api_idempotency (
    principal_id     text NOT NULL,
    project_id       text NOT NULL,
    operation        text NOT NULL,
    key              text NOT NULL,
    request_hash     text NOT NULL,
    response_status  integer,
    response_summary text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (principal_id, project_id, operation, key)
);

-- ---------------------------------------------------------------------------
-- SQLite import mapping (architecture section 13: old/new ID mapping table)
-- ---------------------------------------------------------------------------

CREATE TABLE legacy_id_map (
    source_table text NOT NULL,
    source_id    text NOT NULL,
    target_table text NOT NULL,
    target_id    text NOT NULL,
    metadata     jsonb NOT NULL DEFAULT '{}'::jsonb,
    imported_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source_table, source_id)
);

-- ---------------------------------------------------------------------------
-- Append-only enforcement (DATA-GATE-002)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION maestro_raise_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '%_IMMUTABLE', TG_ARGV[0]
        USING ERRCODE = 'raise_exception',
              HINT = 'append a new fact instead of rewriting history';
END;
$$ LANGUAGE plpgsql;

-- Audit events and local evidence are immutable facts: no UPDATE, no DELETE.
CREATE TRIGGER trg_audit_events_immutable
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION maestro_raise_immutable('AUDIT_EVENT');
CREATE TRIGGER trg_validation_runs_immutable
    BEFORE UPDATE OR DELETE ON validation_runs
    FOR EACH ROW EXECUTE FUNCTION maestro_raise_immutable('VALIDATION_RUN');

-- Inbox/outbox envelope columns are immutable; only dispatch bookkeeping
-- columns may change (status/attempts/available_at/lease_owner/
-- processed_at/updated_at). Rows are never deleted.
CREATE OR REPLACE FUNCTION maestro_envelope_immutable() RETURNS trigger AS $$
BEGIN
    IF (event_id, event_type, event_version, source, project_id, subject,
        occurred_at, correlation_id, causation_id, payload_digest,
        sensitivity, payload) IS DISTINCT FROM
       (NEW.event_id, NEW.event_type, NEW.event_version, NEW.source,
        NEW.project_id, NEW.subject, NEW.occurred_at, NEW.correlation_id,
        NEW.causation_id, NEW.payload_digest, NEW.sensitivity, NEW.payload)
    THEN
        RAISE EXCEPTION 'EVENT_ENVELOPE_IMMUTABLE'
            USING ERRCODE = 'raise_exception',
                  HINT = 'dispatch state may change, the durable envelope may not';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_outbox_envelope_immutable
    BEFORE UPDATE ON outbox_events
    FOR EACH ROW EXECUTE FUNCTION maestro_envelope_immutable();
CREATE TRIGGER trg_inbox_envelope_immutable
    BEFORE UPDATE ON inbox_events
    FOR EACH ROW EXECUTE FUNCTION maestro_envelope_immutable();
CREATE TRIGGER trg_outbox_no_delete
    BEFORE DELETE ON outbox_events
    FOR EACH ROW EXECUTE FUNCTION maestro_raise_immutable('OUTBOX_EVENT');
CREATE TRIGGER trg_inbox_no_delete
    BEFORE DELETE ON inbox_events
    FOR EACH ROW EXECUTE FUNCTION maestro_raise_immutable('INBOX_EVENT');

-- The import mapping is insert-only; re-imports reconcile through
-- legacy_id_map lookups, never rewrites.
CREATE TRIGGER trg_legacy_id_map_immutable
    BEFORE UPDATE OR DELETE ON legacy_id_map
    FOR EACH ROW EXECUTE FUNCTION maestro_raise_immutable('LEGACY_ID_MAP');
